In [24]:
import sys
from pathlib import Path

# https://stackoverflow.com/questions/49264194/import-py-file-in-another-directory-in-jupyter-notebook
module_path = Path.cwd().parent / 'scripts'
if module_path not in sys.path:
    sys.path.append(str(module_path))

In [25]:
import pandas as pd
import utils

## create taxa list

In [ ]:
url = 'https://api.inaturalist.org/v1/observations/taxonomy?taxon_id=47120&verifiable=true'

In [14]:
url ='https://api.inaturalist.org/v1/observations/taxonomy?verifiable=true&spam=false&project_id=273661&taxon_id=47605'
taxa_csv_path = '../processed_data/Taranaki_cnc_2026_Asterales.csv'

In [ ]:
url ='https://api.inaturalist.org/v1/observations/taxonomy?verifiable=true&spam=false&project_id=273661'
taxa_csv_path = '../processed_data/Taranaki_cnc_2026.csv'

In [26]:
url ='https://api.inaturalist.org/v1/observations/taxonomy?verifiable=true&spam=false&project_id=260796'
taxa_csv_path = '../processed_data/San_Antonio_cnc_2026.csv'

In [27]:
taxonomy_data = utils.fetchData(url)
ranks = utils.getSortedRanks(taxonomy_data)
treeData = utils.buildTree(taxonomy_data, 'id', 'parent_id' )

In [28]:
taxonList = []
taxon = dict()

utils.flattenTree(treeData[0], taxonList, taxon)
len(taxonList)

11628

In [17]:
df = utils.createTaxaListCsv(taxonList, ranks)
utils.log_df(df)

(88, 20)

,id,kingdom,phylum,subphylum,class,order,family,subfamily,tribe,subtribe,genus,subgenus,section,complex,species,hybrid,variety,subspecies,descendant_obs_count,direct_obs_count
0,47604,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172,1
1,632885,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,Carduoideae,Cardueae,Carduinae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,2
2,48561,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,Carduoideae,Cardueae,Carduinae,Cirsium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1
3,52989,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,Carduoideae,Cardueae,Carduinae,Cirsium,NaN,NaN,NaN,Cirsium vulgare,NaN,NaN,NaN,5,5
5,60132,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,Carduoideae,Cardueae,Carduinae,Cirsium,NaN,NaN,NaN,Cirsium arvense,NaN,NaN,NaN,4,4

In [18]:
df.to_csv(taxa_csv_path, index=False)

## QC counts

In [9]:
obs_df = pd.read_csv('../raw_data/observations-737949.csv/observations-737949.csv')
utils.log_df(obs_df)

(247, 32)

,id,time_observed_at,user_name,latitude,longitude,species_guess,scientific_name,common_name,iconic_taxon_name,taxon_id,...,taxon_supertribe_name,taxon_tribe_name,taxon_subtribe_name,taxon_genus_name,taxon_genushybrid_name,taxon_species_name,taxon_hybrid_name,taxon_subspecies_name,taxon_variety_name,taxon_form_name
0,352359544,2026-04-23 20:31:04 UTC,Abby L,-39.067951,174.101966,Gallant Soldier,Galinsoga parviflora,Gallant Soldier,Plantae,48178,...,NaN,Millerieae,Galinsoginae,Galinsoga,NaN,Galinsoga parviflora,NaN,NaN,NaN,NaN
1,352447905,2026-04-24 02:17:44 UTC,Liam Aitchison,-39.081793,174.038289,leopard-plant,Farfugium japonicum,leopard-plant,Plantae,322755,...,NaN,Senecioneae,Tussilagininae,Farfugium,NaN,Farfugium japonicum,NaN,NaN,NaN,NaN
2,352462926,2026-04-24 02:53:56 UTC,David Munro,-39.083430,174.075271,Kirk's tree daisy,Brachyglottis kirkii,Kirk's tree daisy,Plantae,400080,...,NaN,Senecioneae,NaN,Brachyglottis,NaN,Brachyglottis kirkii,NaN,NaN,NaN,NaN
3,352465989,2026-04-24 03:25:29 UTC,Abby L,-39.070508,174.084475,Asteroideae,Asteroideae,NaN,Plantae,632790,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,352469649,2026-04-24 03:41:42 UTC,Abby L,-39.069410,174.083201,bluemink,Ageratum houstonianum,bluemink,Plantae,120944,...,NaN,Eupatorieae,Ageratinae,Ageratum,NaN,Ageratum houstonianum,NaN,NaN,NaN,NaN

In [19]:
df = pd.read_csv('../processed_data/Taranaki_cnc_2026_Asterales.csv')
utils.log_df(df)

(88, 20)

,id,kingdom,phylum,subphylum,class,order,family,subfamily,tribe,subtribe,genus,subgenus,section,complex,species,hybrid,variety,subspecies,descendant_obs_count,direct_obs_count
0,47604,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172,1
1,632885,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,Carduoideae,Cardueae,Carduinae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,2
2,48561,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,Carduoideae,Cardueae,Carduinae,Cirsium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1
3,52989,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,Carduoideae,Cardueae,Carduinae,Cirsium,NaN,NaN,NaN,Cirsium vulgare,NaN,NaN,NaN,5,5
4,60132,Plantae,Tracheophyta,Angiospermae,Magnoliopsida,Asterales,Asteraceae,Carduoideae,Cardueae,Carduinae,Cirsium,NaN,NaN,NaN,Cirsium arvense,NaN,NaN,NaN,4,4

In [21]:
set(df['id']) - set(obs_df['taxon_id'])

set()

In [23]:
set(obs_df['taxon_id']) - set(df['id'])

set()

In [20]:
for id, count in obs_df.value_counts(subset=['taxon_id']).items():
    index = df[df['id'] == id].index.values[0]
    count2 = df.at[index, 'direct_obs_count']
    if count != count2:
        print(id[0], 'count:',count, 'count2:',count2)